name: Example

on:
  push:
    branches-ignore:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Call action
      uses: .
      with:
        coverage-file: "testdata/coverage.out"
